tinyMCE.init({
        mode : "textareas",
        theme : "advanced",
        plugins : "safari,insertdatetime,searchreplace",
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,fontsizeselect,forecolor,|,undo,redo,|,search,replace,|,link,unlink,anchor,image,code,|,insertdate,inserttime,charmap",
        theme_advanced_buttons2 : "",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        //content_css : "/css/word.css",
        plugi2n_insertdate_dateFormat : "%Y-%m-%d",
        plugi2n_insertdate_timeFormat : "%H:%M:%S",
        language : "ru",
        paste_use_dialog : false,
        theme_advanced_resizing : true,
        theme_advanced_resize_horizontal : true,
        paste_auto_cleanup_on_paste : false,
        paste_convert_headers_to_strong : false,
        paste_remove_spans : false,
        paste_remove_styles : false,
        relative_urls : true,
        apply_source_formatting : false,
        cleanup : false,
        convert_urls : false,
        convert_fonts_to_spans : false
    });
