<?php $html->addCrumb('Something', '/maina'); ?>
<?php $html->addCrumb('Something else', '/maina/index'); ?>
<div class="MainPage">
   WellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWellWell
   WellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWellWellWell WellWell
</div>